document.write("<center>")
document.write("<h3> * screen 객체 * </h3>")
document.write("</center>")
document.write("<hr><br> 사용 가능한 화면의 높이 ===> " , screen.availHeight)
document.write("<br><br> 사용 가능한 화면의 너비 ===> " , screen.availWidth)
document.write("<hr><br> 사용 가능한 색상 수 ===> " , screen.colorDepth)
document.write("<hr><br> [ 현 재 해 상 도 ] ")
document.write("<br><br> 화면 높이 ===> " , screen.height)
document.write("<br> 화면 너비 ===> " , screen.width)
document.write("<hr><br> 픽셀당 비트 수 ===> " , screen.pixelDepth)