document.write('<center>') 
document.write('<hr>')
document.write('<h3>')
document.write('* 그림 출력하기 *')
document.write('</h3>')
document.write('<hr>')
document.write('<img src="images\\성백.jpg">')
document.write('<hr>')
document.write('</center>')